"""Self-contained interactive HTML/JS visualization renderer."""

from __future__ import annotations

import json

from citation_tree.models import CitationTree


def render_html_reference_tree(
    tree: CitationTree,
    output_path: str,
    has_reference: bool = True,
    has_citation: bool = True,
):
    """Write a self-contained interactive HTML page for the reference tree."""

    tree_json = json.dumps(tree.to_json(), ensure_ascii=False)
    root_title_safe = (
        tree.root.title[:60].replace("'", "&#39;").replace('"', "&quot;")
    )
    ref_tab = (
        '<a class="tab active" href="reference_tree.html">Reference Tree</a>'
        if has_reference
        else '<span class="tab disabled" title="Failed to generate">Reference Tree</span>'
    )
    cite_tab = (
        '<a class="tab" href="citation_tree.html">Citation Tree</a>'
        if has_citation
        else '<span class="tab disabled" title="Failed to generate">Citation Tree</span>'
    )

    html = (
        '<!DOCTYPE html>\n<html lang="en">\n<head>\n'
        '<meta charset="UTF-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        f"<title>Reference Tree – {root_title_safe}</title>\n"
        "<style>\n"
        "  :root {\n"
        "    --bg: #0f1117; --surface: #1a1d27; --border: #2a2d3a;\n"
        "    --text: #e1e4ed; --muted: #8b8fa3; --accent: #6c8cff;\n"
        "    --accent2: #a78bfa; --green: #34d399; --orange: #fb923c;\n"
        "    --red: #f87171;\n"
        "  }\n"
        "  * { margin:0; padding:0; box-sizing:border-box; }\n"
        "  body {\n"
        "    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;\n"
        "    background: var(--bg); color: var(--text); line-height:1.5;\n"
        "    overflow-x: hidden;\n"
        "  }\n"
        "  .tabs { display:flex; gap:12px; padding:16px 24px; border-bottom:1px solid var(--border); background:#141927; }\n"
        "  .tab { flex:1; text-align:center; padding:14px 12px; border-radius:10px; border:1px solid var(--border); color:var(--text); text-decoration:none; font-weight:600; font-size:0.95rem; background:var(--surface); }\n"
        "  .tab.active { border-color:var(--accent); box-shadow:0 0 0 2px rgba(108,140,255,.2); }\n"
        "  .tab.disabled { opacity:.45; cursor:not-allowed; }\n"
        "  .container { display: flex; min-height: calc(100vh - 84px); align-items: flex-start; }\n"
        "  #tree-panel { flex: 1; padding: 24px; overflow: visible; }\n"
        "  #detail-panel {\n"
        "    width: 420px; border-left: 1px solid var(--border);\n"
        "    background: var(--surface); overflow: visible; padding: 24px;\n"
        "    transition: width 0.2s;\n"
        "  }\n"
        "  #detail-panel.hidden { width: 0; padding: 0; overflow: hidden; }\n"
        "  .node {\n"
        "    background: var(--surface); border: 1px solid var(--border);\n"
        "    border-radius: 10px; padding: 14px 18px; margin-bottom: 8px;\n"
        "    cursor: pointer; transition: all 0.15s;\n"
        "  }\n"
        "  .node:hover { border-color: var(--accent); transform: translateX(3px); }\n"
        "  .node.selected { border-color: var(--accent); box-shadow: 0 0 0 2px rgba(108,140,255,.25); }\n"
        "  .node.root { border-left: 3px solid var(--accent); }\n"
        "  .node-title { font-weight: 600; font-size: 0.95rem; margin-bottom: 4px; }\n"
        "  .node-meta { font-size: 0.78rem; color: var(--muted); }\n"
        "  .node-meta span { margin-right: 12px; }\n"
        "  .badge {\n"
        "    display:inline-block; padding: 2px 8px; border-radius: 4px;\n"
        "    font-size: 0.7rem; font-weight: 600; text-transform: uppercase;\n"
        "  }\n"
        "  .badge.ref { background: rgba(52,211,153,.15); color: var(--green); }\n"
        "  .badge.cite { background: rgba(251,146,60,.15); color: var(--orange); }\n"
        "  .badge.rel { background: rgba(167,139,250,.15); color: var(--accent2); }\n"
        "  .depth-indent { padding-left: 28px; border-left: 2px solid var(--border); margin-left: 12px; }\n"
        "  .detail-section { margin-bottom: 20px; }\n"
        "  .detail-section h3 {\n"
        "    font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.08em;\n"
        "    color: var(--muted); margin-bottom: 8px;\n"
        "  }\n"
        "  .detail-section p, .detail-section ul { font-size: 0.88rem; }\n"
        "  .detail-section ul { padding-left: 18px; }\n"
        "  .improvement-box {\n"
        "    background: rgba(108,140,255,.08); border: 1px solid rgba(108,140,255,.2);\n"
        "    border-radius: 8px; padding: 12px 16px; font-size: 0.88rem; line-height: 1.6;\n"
        "  }\n"
        "  .sim-bar { height: 6px; border-radius: 3px; background: var(--border); margin-top: 6px; }\n"
        "  .sim-bar-fill { height:100%; border-radius: 3px; background: var(--accent); }\n"
        "  .stat-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 20px; }\n"
        "  .stat { background: var(--surface); border:1px solid var(--border); border-radius:8px; padding:12px; text-align:center; }\n"
        "  .stat .val { font-size:1.4rem; font-weight:700; color: var(--accent); }\n"
        "  .stat .lbl { font-size:.7rem; color:var(--muted); text-transform:uppercase; letter-spacing:.06em; }\n"
        "  a { color: var(--accent); text-decoration: none; }\n"
        "  a:hover { text-decoration: underline; }\n"
        "</style>\n</head>\n<body>\n"
        f'<div class="tabs">{ref_tab}{cite_tab}</div>\n'
        '<div class="container">\n'
        '  <div id="tree-panel">\n'
        '    <div id="tree-root"></div>\n'
        "  </div>\n"
        '  <div id="detail-panel" class="hidden">\n'
        '    <div id="detail-content"></div>\n'
        "  </div>\n"
        "</div>\n\n"
        "<script>\n"
        f"const DATA = {tree_json};\n\n"
        "const papers = DATA.papers;\n"
        "const edges  = DATA.edges;\n\n"
        "// Build children map\n"
        "const children = {};\n"
        "edges.forEach(e => {\n"
        "  if (!children[e.source]) children[e.source] = [];\n"
        "  children[e.source].push({ id: e.target, relation: e.relation });\n"
        "});\n"
        "Object.keys(children).forEach(k => {\n"
        "  children[k].sort((a, b) => (papers[a.id]?.year || 9999) - (papers[b.id]?.year || 9999));\n"
        "});\n\n"
        "function badgeFor(r) {\n"
        "  if (r === 'reference') return '<span class=\"badge ref\">ref</span>';\n"
        "  if (r === 'citation')  return '<span class=\"badge cite\">cite</span>';\n"
        "  return '<span class=\"badge rel\">related</span>';\n"
        "}\n\n"
        "function renderNode(id, relation, isRoot) {\n"
        "  const p = papers[id];\n"
        "  if (!p) return '';\n"
        "  const cls = isRoot ? 'node root' : 'node';\n"
        "  const year = p.year || '\\u2014';\n"
        "  const badge = isRoot ? '' : badgeFor(relation);\n"
        "  const sim = p.similarity_to_parent\n"
        "    ? `&nbsp;\\u00b7&nbsp;sim ${Math.round(p.similarity_to_parent*100)}%`\n"
        "    : '';\n"
        "  let kidHtml = '';\n"
        "  if (children[id]) {\n"
        "    kidHtml = '<div class=\"depth-indent\">' +\n"
        "      children[id].map(c => renderNode(c.id, c.relation, false)).join('') +\n"
        "      '</div>';\n"
        "  }\n"
        "  return `\n"
        "    <div class=\"${cls}\" data-id=\"${id}\" onclick=\"selectNode('${id}', event)\">\n"
        "      <div class=\"node-title\">${p.title}</div>\n"
        "      <div class=\"node-meta\">\n"
        "        <span>${year}</span>\n"
        "        ${badge}${sim}\n"
        "      </div>\n"
        "    </div>\n"
        "    ${kidHtml}\n"
        "  `;\n"
        "}\n\n"
        "function renderTree() {\n"
        "  const root = DATA.root_id;\n"
        "  document.getElementById('tree-root').innerHTML = renderNode(root, '', true);\n"
        "}\n\n"
        "function selectNode(id, ev) {\n"
        "  if (ev) ev.stopPropagation();\n"
        "  document.querySelectorAll('.node').forEach(n => n.classList.remove('selected'));\n"
        "  const el = document.querySelector(`.node[data-id=\"${id}\"]`);\n"
        "  if (el) el.classList.add('selected');\n"
        "  const p = papers[id];\n"
        "  const panel = document.getElementById('detail-panel');\n"
        "  const content = document.getElementById('detail-content');\n"
        "  panel.classList.remove('hidden');\n"
        "\n"
        "  // Helper to clean any remaining LaTeX from text\n"
        "  function cleanLatex(text) {\n"
        "    if (!text) return text;\n"
        "    return text\n"
        "      .replace(/\\$[^$]+\\$/g, '')\n"
        "      .replace(/\\\\\\([^)]+\\\\\\)/g, '')\n"
        "      .replace(/\\\\\\[[^\\]]+\\\\\\]/g, '')\n"
        "      .replace(/\\\\[a-zA-Z]+\\{[^}]*\\}/g, '')\n"
        "      .replace(/\\\\[a-zA-Z]+/g, '')\n"
        "      .replace(/[{}\\\\]/g, '')\n"
        "      .replace(/[_^]+/g, '')\n"
        "      .replace(/\\s+/g, ' ')\n"
        "      .trim();\n"
        "  }\n"
        "\n"
        "  let html = `<div class=\"detail-section\"><h3>Title</h3><p>${cleanLatex(p.title)}</p></div>`;\n"
        "  if (p.authors.length)\n"
        "    html += `<div class=\"detail-section\"><h3>Authors</h3><p>${p.authors.join(', ')}</p></div>`;\n"
        "  html += `<div class=\"detail-section\"><h3>Details</h3>\n"
        "    <p>Year: ${p.year||'\\u2014'} &nbsp;|&nbsp; Source: ${p.source}</p></div>`;\n"
        "  if (p.abstract)\n"
        "    html += `<div class=\"detail-section\"><h3>Abstract</h3><p>${cleanLatex(p.abstract)}</p></div>`;\n"
        "  if (p.improvement && p.improvement.length > 10) {\n"
        "    const cleanedImprovement = cleanLatex(p.improvement);\n"
        "    // Only show if it looks like actual content, not a prompt echo\n"
        "    if (cleanedImprovement.length > 20 && !cleanedImprovement.includes('Paper A:') && !cleanedImprovement.includes('Original paper:')) {\n"
        "      html += `<div class=\"detail-section\"><h3>How the parent (citing paper) improves on this referenced paper</h3>\n"
        "        <div class=\"improvement-box\">${cleanedImprovement}</div></div>`;\n"
        "    }\n"
        "  }\n"
        "  if (p.similarity_to_parent)\n"
        "    html += `<div class=\"detail-section\"><h3>Semantic similarity to parent</h3>\n"
        "      <div class=\"sim-bar\"><div class=\"sim-bar-fill\" style=\"width:${Math.round(p.similarity_to_parent*100)}%\"></div></div>\n"
        "      <p style=\"font-size:.8rem;color:var(--muted);margin-top:4px\">${Math.round(p.similarity_to_parent*100)}%</p></div>`;\n"
        "  if (p.categories && p.categories.length)\n"
        "    html += `<div class=\"detail-section\"><h3>Categories</h3><p>${p.categories.join(', ')}</p></div>`;\n"
        "  if (p.url)\n"
        "    html += `<div class=\"detail-section\"><a href=\"${p.url}\" target=\"_blank\">View paper \\u2197</a></div>`;\n"
        "  content.innerHTML = html;\n"
        "}\n\n"
        "renderTree();\n\n"
        "// Stats bar\n"
        "(() => {\n"
        "  const vals = Object.values(papers);\n"
        "  const years = vals.map(p => p.year).filter(Boolean);\n"
        "  const statHtml = `\n"
        "    <div class=\"stat-grid\">\n"
        "      <div class=\"stat\"><div class=\"val\">${vals.length}</div><div class=\"lbl\">Papers</div></div>\n"
        "      <div class=\"stat\"><div class=\"val\">${edges.length}</div><div class=\"lbl\">Edges</div></div>\n"
        "      <div class=\"stat\"><div class=\"val\">${years.length ? Math.min(...years) : '\\u2014'}</div><div class=\"lbl\">Earliest</div></div>\n"
        "      <div class=\"stat\"><div class=\"val\">${years.length ? Math.max(...years) : '\\u2014'}</div><div class=\"lbl\">Latest</div></div>\n"
        "    </div>`;\n"
        "  document.getElementById('tree-root').insertAdjacentHTML('afterbegin', statHtml);\n"
        "})();\n"
        "</script>\n</body>\n</html>"
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"\n  Visualization saved to: {output_path}")





def render_html_citation_tree(
    tree: CitationTree,
    output_path: str,
    has_reference: bool = True,
    has_citation: bool = True,
):
    """Write a self-contained interactive HTML page for the citation tree."""

    tree_json = json.dumps(tree.to_json(), ensure_ascii=False)
    root_title_safe = (
        tree.root.title[:60].replace("'", "&#39;").replace('"', "&quot;")
    )
    ref_tab = (
        '<a class="tab" href="reference_tree.html">Reference Tree</a>'
        if has_reference
        else '<span class="tab disabled" title="Failed to generate">Reference Tree</span>'
    )
    cite_tab = (
        '<a class="tab active" href="citation_tree.html">Citation Tree</a>'
        if has_citation
        else '<span class="tab disabled" title="Failed to generate">Citation Tree</span>'
    )

    html = (
        '<!DOCTYPE html>\n<html lang="en">\n<head>\n'
        '<meta charset="UTF-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        f"<title>Citation Tree – {root_title_safe}</title>\n"
        "<style>\n"
        "  :root {\n"
        "    --bg: #0f1117; --surface: #1a1d27; --border: #2a2d3a;\n"
        "    --text: #e1e4ed; --muted: #8b8fa3; --accent: #6c8cff;\n"
        "    --accent2: #a78bfa; --green: #34d399; --orange: #fb923c;\n"
        "    --red: #f87171;\n"
        "  }\n"
        "  * { margin:0; padding:0; box-sizing:border-box; }\n"
        "  body {\n"
        "    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;\n"
        "    background: var(--bg); color: var(--text); line-height:1.5;\n"
        "    overflow-x: hidden;\n"
        "  }\n"
        "  .tabs { display:flex; gap:12px; padding:16px 24px; border-bottom:1px solid var(--border); background:#141927; }\n"
        "  .tab { flex:1; text-align:center; padding:14px 12px; border-radius:10px; border:1px solid var(--border); color:var(--text); text-decoration:none; font-weight:600; font-size:0.95rem; background:var(--surface); }\n"
        "  .tab.active { border-color:var(--accent); box-shadow:0 0 0 2px rgba(108,140,255,.2); }\n"
        "  .tab.disabled { opacity:.45; cursor:not-allowed; }\n"
        "  .container { display: flex; min-height: calc(100vh - 84px); align-items: flex-start; }\n"
        "  #tree-panel { flex: 1; padding: 24px; overflow: visible; }\n"
        "  #detail-panel {\n"
        "    width: 420px; border-left: 1px solid var(--border);\n"
        "    background: var(--surface); overflow: visible; padding: 24px;\n"
        "    transition: width 0.2s;\n"
        "  }\n"
        "  #detail-panel.hidden { width: 0; padding: 0; overflow: hidden; }\n"
        "  .node {\n"
        "    background: var(--surface); border: 1px solid var(--border);\n"
        "    border-radius: 10px; padding: 14px 18px; margin-bottom: 8px;\n"
        "    cursor: pointer; transition: all 0.15s;\n"
        "  }\n"
        "  .node:hover { border-color: var(--accent); transform: translateX(3px); }\n"
        "  .node.selected { border-color: var(--accent); box-shadow: 0 0 0 2px rgba(108,140,255,.25); }\n"
        "  .node.root { border-left: 3px solid var(--accent); }\n"
        "  .node-title { font-weight: 600; font-size: 0.95rem; margin-bottom: 4px; }\n"
        "  .node-meta { font-size: 0.78rem; color: var(--muted); }\n"
        "  .node-meta span { margin-right: 12px; }\n"
        "  .badge {\n"
        "    display:inline-block; padding: 2px 8px; border-radius: 4px;\n"
        "    font-size: 0.7rem; font-weight: 600; text-transform: uppercase;\n"
        "  }\n"
        "  .badge.ref { background: rgba(52,211,153,.15); color: var(--green); }\n"
        "  .badge.cite { background: rgba(251,146,60,.15); color: var(--orange); }\n"
        "  .badge.rel { background: rgba(167,139,250,.15); color: var(--accent2); }\n"
        "  .depth-indent { padding-left: 28px; border-left: 2px solid var(--border); margin-left: 12px; }\n"
        "  .detail-section { margin-bottom: 20px; }\n"
        "  .detail-section h3 {\n"
        "    font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.08em;\n"
        "    color: var(--muted); margin-bottom: 8px;\n"
        "  }\n"
        "  .detail-section p, .detail-section ul { font-size: 0.88rem; }\n"
        "  .detail-section ul { padding-left: 18px; }\n"
        "  .improvement-box {\n"
        "    background: rgba(108,140,255,.08); border: 1px solid rgba(108,140,255,.2);\n"
        "    border-radius: 8px; padding: 12px 16px; font-size: 0.88rem; line-height: 1.6;\n"
        "  }\n"
        "  .sim-bar { height: 6px; border-radius: 3px; background: var(--border); margin-top: 6px; }\n"
        "  .sim-bar-fill { height:100%; border-radius: 3px; background: var(--accent); }\n"
        "  .stat-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 20px; }\n"
        "  .stat { background: var(--surface); border:1px solid var(--border); border-radius:8px; padding:12px; text-align:center; }\n"
        "  .stat .val { font-size:1.4rem; font-weight:700; color: var(--accent); }\n"
        "  .stat .lbl { font-size:.7rem; color:var(--muted); text-transform:uppercase; letter-spacing:.06em; }\n"
        "  a { color: var(--accent); text-decoration: none; }\n"
        "  a:hover { text-decoration: underline; }\n"
        "</style>\n</head>\n<body>\n"
        f'<div class="tabs">{ref_tab}{cite_tab}</div>\n'
        '<div class="container">\n'
        '  <div id="tree-panel">\n'
        '    <div id="tree-root"></div>\n'
        "  </div>\n"
        '  <div id="detail-panel" class="hidden">\n'
        '    <div id="detail-content"></div>\n'
        "  </div>\n"
        "</div>\n\n"
        "<script>\n"
        f"const DATA = {tree_json};\n\n"
        "const papers = DATA.papers;\n"
        "const edges  = DATA.edges;\n\n"
        "// Build children map\n"
        "const children = {};\n"
        "edges.forEach(e => {\n"
        "  if (!children[e.source]) children[e.source] = [];\n"
        "  children[e.source].push({ id: e.target, relation: e.relation });\n"
        "});\n"
        "Object.keys(children).forEach(k => {\n"
        "  children[k].sort((a, b) => (papers[a.id]?.year || 9999) - (papers[b.id]?.year || 9999));\n"
        "});\n\n"
        "function badgeFor(r) {\n"
        "  if (r === 'reference') return '<span class=\"badge ref\">ref</span>';\n"
        "  if (r === 'citation')  return '<span class=\"badge cite\">cite</span>';\n"
        "  return '<span class=\"badge rel\">related</span>';\n"
        "}\n\n"
        "function renderNode(id, relation, isRoot) {\n"
        "  const p = papers[id];\n"
        "  if (!p) return '';\n"
        "  const cls = isRoot ? 'node root' : 'node';\n"
        "  const year = p.year || '\\u2014';\n"
        "  const badge = isRoot ? '' : badgeFor(relation);\n"
        "  const sim = p.similarity_to_parent\n"
        "    ? `&nbsp;\\u00b7&nbsp;sim ${Math.round(p.similarity_to_parent*100)}%`\n"
        "    : '';\n"
        "  let kidHtml = '';\n"
        "  if (children[id]) {\n"
        "    kidHtml = '<div class=\"depth-indent\">' +\n"
        "      children[id].map(c => renderNode(c.id, c.relation, false)).join('') +\n"
        "      '</div>';\n"
        "  }\n"
        "  return `\n"
        "    <div class=\"${cls}\" data-id=\"${id}\" onclick=\"selectNode('${id}', event)\">\n"
        "      <div class=\"node-title\">${p.title}</div>\n"
        "      <div class=\"node-meta\">\n"
        "        <span>${year}</span>\n"
        "        ${badge}${sim}\n"
        "      </div>\n"
        "    </div>\n"
        "    ${kidHtml}\n"
        "  `;\n"
        "}\n\n"
        "function renderTree() {\n"
        "  const root = DATA.root_id;\n"
        "  document.getElementById('tree-root').innerHTML = renderNode(root, '', true);\n"
        "}\n\n"
        "function selectNode(id, ev) {\n"
        "  if (ev) ev.stopPropagation();\n"
        "  document.querySelectorAll('.node').forEach(n => n.classList.remove('selected'));\n"
        "  const el = document.querySelector(`.node[data-id=\"${id}\"]`);\n"
        "  if (el) el.classList.add('selected');\n"
        "  const p = papers[id];\n"
        "  const panel = document.getElementById('detail-panel');\n"
        "  const content = document.getElementById('detail-content');\n"
        "  panel.classList.remove('hidden');\n"
        "\n"
        "  // Helper to clean any remaining LaTeX from text\n"
        "  function cleanLatex(text) {\n"
        "    if (!text) return text;\n"
        "    return text\n"
        "      .replace(/\\$[^$]+\\$/g, '')\n"
        "      .replace(/\\\\\\([^)]+\\\\\\)/g, '')\n"
        "      .replace(/\\\\\\[[^\\]]+\\\\\\]/g, '')\n"
        "      .replace(/\\\\[a-zA-Z]+\\{[^}]*\\}/g, '')\n"
        "      .replace(/\\\\[a-zA-Z]+/g, '')\n"
        "      .replace(/[{}\\\\]/g, '')\n"
        "      .replace(/[_^]+/g, '')\n"
        "      .replace(/\\s+/g, ' ')\n"
        "      .trim();\n"
        "  }\n"
        "\n"
        "  let html = `<div class=\"detail-section\"><h3>Title</h3><p>${cleanLatex(p.title)}</p></div>`;\n"
        "  if (p.authors.length)\n"
        "    html += `<div class=\"detail-section\"><h3>Authors</h3><p>${p.authors.join(', ')}</p></div>`;\n"
        "  html += `<div class=\"detail-section\"><h3>Details</h3>\n"
        "    <p>Year: ${p.year||'\\u2014'} &nbsp;|&nbsp; Source: ${p.source}</p></div>`;\n"
        "  if (p.abstract)\n"
        "    html += `<div class=\"detail-section\"><h3>Abstract</h3><p>${cleanLatex(p.abstract)}</p></div>`;\n"
        "  if (p.improvement && p.improvement.length > 10) {\n"
        "    const cleanedImprovement = cleanLatex(p.improvement);\n"
        "    // Only show if it looks like actual content, not a prompt echo\n"
        "    if (cleanedImprovement.length > 20 && !cleanedImprovement.includes('Paper A:') && !cleanedImprovement.includes('Original paper:')) {\n"
        "      html += `<div class=\"detail-section\"><h3>How this citing paper improves on the cited parent</h3>\n"
        "        <div class=\"improvement-box\">${cleanedImprovement}</div></div>`;\n"
        "    }\n"
        "  }\n"
        "  if (p.similarity_to_parent)\n"
        "    html += `<div class=\"detail-section\"><h3>Semantic similarity to parent</h3>\n"
        "      <div class=\"sim-bar\"><div class=\"sim-bar-fill\" style=\"width:${Math.round(p.similarity_to_parent*100)}%\"></div></div>\n"
        "      <p style=\"font-size:.8rem;color:var(--muted);margin-top:4px\">${Math.round(p.similarity_to_parent*100)}%</p></div>`;\n"
        "  if (p.categories && p.categories.length)\n"
        "    html += `<div class=\"detail-section\"><h3>Categories</h3><p>${p.categories.join(', ')}</p></div>`;\n"
        "  if (p.url)\n"
        "    html += `<div class=\"detail-section\"><a href=\"${p.url}\" target=\"_blank\">View paper \\u2197</a></div>`;\n"
        "  content.innerHTML = html;\n"
        "}\n\n"
        "renderTree();\n\n"
        "// Stats bar\n"
        "(() => {\n"
        "  const vals = Object.values(papers);\n"
        "  const years = vals.map(p => p.year).filter(Boolean);\n"
        "  const statHtml = `\n"
        "    <div class=\"stat-grid\">\n"
        "      <div class=\"stat\"><div class=\"val\">${vals.length}</div><div class=\"lbl\">Papers</div></div>\n"
        "      <div class=\"stat\"><div class=\"val\">${edges.length}</div><div class=\"lbl\">Edges</div></div>\n"
        "      <div class=\"stat\"><div class=\"val\">${years.length ? Math.min(...years) : '\\u2014'}</div><div class=\"lbl\">Earliest</div></div>\n"
        "      <div class=\"stat\"><div class=\"val\">${years.length ? Math.max(...years) : '\\u2014'}</div><div class=\"lbl\">Latest</div></div>\n"
        "    </div>`;\n"
        "  document.getElementById('tree-root').insertAdjacentHTML('afterbegin', statHtml);\n"
        "})();\n"
        "</script>\n</body>\n</html>"
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"\n  Visualization saved to: {output_path}")


